### ISSUE TITLE
Metrics sub-roles are not visible to Ansible in default configuration

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#34]
The metrics role uses the following set of sub-roles:

- performancecopilot_metrics_bpftrace
- performancecopilot_metrics_mssql
- performancecopilot_metrics_elasticsearch
- performancecopilot_metrics_pcp
- performancecopilot_metrics_grafana
- performancecopilot_metrics_redis

Unfortunately these sub-roles are not visible to Ansible in the default configuration.

Let's have a playbook `/root/myplaybook.yml` in root's home directory: 
```yaml
# SPDX-License-Identifier: MIT
---
- name: My playbook
  hosts: all

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_from_elasticsearch: yes
```
When the playbook is run using this command `ansible-playbook /root/myplaybook.yml` it fails with the following error:
```
TASK [Setup Elasticsearch metrics] ********************************************************
ERROR! the role 'performancecopilot_metrics_pcp' was not found in /root/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/root

The error appears to be in '/usr/share/ansible/roles/metrics/roles/performancecopilot_metrics_elasticsearch/tasks/main.yml': line 24, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  import_role:
    name: performancecopilot_metrics_pcp
          ^ here
```
_Note: a patch for [issue #33 ](https://github.com/linux-system-roles/metrics/issues/33) has been applied here as the original `pcp` role does not exists at all_

**The issue is: In the default installation/configuration the metrics role can not find its own sub-roles.**
