### ISSUE TITLE
Configuration of Elasticsearch, MSSQL and BPFtrace agents fail

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#35]
Configuration of Elasticsearch agent fails with the following error:
```
fatal: [10.0.139.221]: FAILED! => {"changed": false, "checksum": "c076ec4531eacb5b8058b3a0a5b82a1218acf987", "msg": "Destination directory /etc/pcp/elasticsearch does not exist"}
```

The issue occurs when the following playbook runs:
```yaml
# SPDX-License-Identifier: MIT
---
- name: Install Elastic search
  hosts: all

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_from_elasticsearch: yes
```

The problem is in `roles/performancecopilot_metrics_elasticsearch/tasks/main.yml` file in section named `Ensure PCP Elasticsearch agent is configured`, where ansible is trying to install an elasticsearch config file from a template to `/etc/pcp/elasticsearch` directory. Unfortunately the destination directory does not exists, because at that time there is no pcp-pmda-elasticsearch package installed yet. The pcp-pmda-elasticsearch package owns the `/etc/pcp/elasticsearch` directory.

- _Note 1: The same issue applies to `roles/performancecopilot_metrics_mssql/tasks/main.yml`* and `pcp-pmda-mssql`_
- _Note 2: The same issue applies to `roles/performancecopilot_metrics_bpftrace/tasks/main.yml`* and `pcp-pmda-bpftrace`_
