### ISSUE TITLE
PMCD is not restarted after installation of ElasticSearch agent

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#46]
When I try to enable import of metrics from Elastic Search, I need to manually restart `pmcd` on the host machine after a playbook run. Without the restart elasticsearch agent is not registered.

The role installs `pcp-pmda-elasticsearch` package and creates `/var/lib/pcp/pmdas/elasticsearch/.NeedInstall` file. However the `pmcd` is not restarted then, so pmcd startup script does not register it.

I am using a playbook like this one:
```yaml
# SPDX-License-Identifier: MIT
---
- name: Make ElasticSearch metrics available
  hosts: all

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_from_elasticsearch: yes
```

_Note:_ When I run the playbook above I do not see any execution of `restart pmcd` handler in the log. However, if the playbook explicitly forces execution of handlers ...

```yaml
# SPDX-License-Identifier: MIT
---
- name: Make ElasticSearch metrics available
  hosts: all

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_from_elasticsearch: yes

  tasks:
    - name: Flush handlers
      meta: flush_handlers
```
... then I see the following message in the log:
```
RUNNING HANDLER [performancecopilot_metrics_pcp : restart pmcd] ***************************
skipping: [10.0.137.131]
```
So it looks like the role sends a notification to restart `pmcd` however the handler is skipped for some reason.

**Comment by kurik** [comment]
The same issue applies for MSSQL and BPFTRACE agents.
```yaml
# SPDX-License-Identifier: MIT
---
- name: Make MSSQL and BPFTRACE metrics available
  hosts: all

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_from_mssql: yes
        metrics_from_bpftrace: yes
```
