### ISSUE TITLE
PMCD is not restarted on RHEL platform

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#50]
I have a playbook like this:

```yaml
# SPDX-License-Identifier: MIT
---
- name: Ensure that MSSQL is configured
  hosts: all

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_from_mssql: yes

  pre_tasks:
    - name: Ensure python3-pyodbc is installed
      package:
        name: python3-pyodbc
        state: present

  tasks:
    - name: Check if MSSQL functionality works
      shell: pmprobe -I pmcd.agent.name | grep -w '"mssql"'
```

On Fedora and CentOS this works just fine. However on RHEL it fails with the following error message:

`
TASK [Check if mssql pmda is registered] **************************************************
fatal: [10.0.139.219]: FAILED! => {"changed": true, "cmd": "pmprobe -I pmcd.agent.name | grep -w '\"mssql\"'", "delta": "0:00:00.012001", "end": "2021-01-29 04:59:55.181201", "msg": "non-zero return code", "rc": 1, "start": "2021-01-29 04:59:55.169200", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
`

... so the registration of the PMDA has not finished. There is `/var/lib/pcp/pmdas/mssql/.NeedInstall` file created, but `pmcd` is not restarted.

The reason is IMO somehow related to `pcp-zeroconf` package, which starts and enables `pmcd` service only on RHEL platform, while on Fedora and CentOS the `pmcd` is not started nor enabled after boot.
