### ISSUE TITLE
pmrepconf is not available on all platforms

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#52]
I have the following playbook:

```yaml
# SPDX-License-Identifier: MIT
---
- name: Check if pcp2elasticsearch has been deployed
  hosts: all

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_into_elasticsearch: yes

  tasks:
    - name: Check if pcp2elasticsearch is installed
      command: test -x /usr/bin/pcp2elasticsearch
```

This playbook fails on the following distros:
* RHEL <= 8.3
* Fedora <= 32
* CentoOS
*(I do not have a Debian box available, so I can not provide infor for this distro)*

The error message printed by Ansible is as follows:

`fatal: [10.0.138.13]: FAILED! => {"changed": false, "msg": "Unable to start service pcp2elasticsearch: Job for pcp2elasticsearch.service failed because the control process exited with error code.\nSee \"systemctl status pcp2elasticsearch.service\" and \"journalctl -xe\" for details.\n"}`

The `journalctl -xe` shows as the real reason:

`pcp2elasticsearch.service: Failed at step EXEC spawning /usr/bin/pmrepconf: No such file or directory`

The `pmrepconf` tool is used in unit file of the `pcp2elasticsearch.service` service. The issue is that `pmrepconf` tool has been introduced in pcp version 5.2.0, while all the distros mentioned above are using older pcp version where this tool is not available.

If this is intentional and the `metrics_into_elasticsearch` functionality should work only with the pcp >= 5.2.0, let me know and I will modify my tests accordingly.
