### ISSUE TITLE
The role fails on RHEL-6 due to missing "cyrus-sasl-scram" package

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#55]
Let's have a following playbook:

```yaml
# SPDX-License-Identifier: MIT
---
- name: Ensure that the role runs
  hosts: all

  roles:
    - role: linux-system-roles.metrics
```

When this playbook runs on RHEL-6, it fails with the following error message:

```
fatal: [10.0.139.92]: FAILED! => {"changed": false, "msg": "No package matching 'cyrus-sasl-scram' found available, installed or updated", "rc": 126, "results": ["cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64 providing cyrus-sasl-lib is already installed", "No package matching 'cyrus-sasl-scram' found available, installed or updated"]}
```

IMO the reason is in file `roles/performancecopilot_metrics_pcp/vars/RedHat.yml` where this package is requested to be installed. Unfortunately the  'cyrus-sasl-scram' package has been introduced in RHEL/CentOS >= 7 and it is not available on RHEL-6 nor on CentOS-6.

While on CentOS the 'cyrus-sasl-scram' package is requested only on CentOS-7 and CentOS-8 (in `roles/performancecopilot_metrics_pcp/vars/CentOS_8.yml` and `roles/performancecopilot_metrics_pcp/vars/CentOS_7.yml` files), on RHEL the Ansible tries to install it also on RHEL-6.
