### ISSUE TITLE
do not use ignore_errors: yes

### ISSUE THREAD

**Issue by richm** [linux-system-roles/metrics#65]
Do not use `ignore_errors: yes` as in https://github.com/linux-system-roles/metrics/blob/master/roles/elasticsearch/tasks/main.yml#L62
If it is necessary to ignore errors from the task, the task should `register` the output, then have a separate task to `fail` in case there are "real" errors, so as not to mask any unexpected errors.

**Comment by natoscott** [comment]
Hmm, OK - the Ansible docs seemed to suggest that 'real' errors would still be detected and reported, but I've not used this before.  This is to avoid test failures where no elasticsearch server is available, causing the pcp2elasticsearch service to 'fail' (expectedly).

I'll rework it to use register anyway though, sounds like a good option here.

**Comment by natoscott** [comment]
@richm hmm, not as straightforward as I thought - here's a link to an example CI failure log:
https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-metrics-pull-linux-system-roles_metrics-68-6b9c539-fedora-33-20210203-055457/artifacts/ansible.log

... so even with using 'register', we don't get to the stage of being able to look at the output, because the service task failed and the play bailed immediately.  I'm not finding any other way to handle this without ignoring the error... any other options I can look at for that aspect?  Thanks!

**Comment by richm** [comment]
I think we can solve this problem by using `register:` and `failed_when:` - see https://github.com/linux-system-roles/metrics/pull/69

**Comment by richm** [comment]
> I think we can solve this problem by using `register:` and `failed_when:` - see #69

Nope, not without getting detailed output from the service failure and parsing it.

I think the problem is that the the task should be skipped.
```yaml
- name: Ensure PCP Elasticsearch export is running and enabled on boot
  service:
    name: pcp2elasticsearch
    state: started
    enabled: yes
  when:
    - elasticsearch_metrics_provider == 'pcp'
    - elasticsearch_export_metrics|d(false)|bool
```
What other condition can be used with the `when` here to ensure that this task is skipped?  The other problem with `ignore_error` is that it will cause this service to be enabled - which will then show errors if someone is looking at the system - and they won't know if it is safe to ignore.
